<?php require_once APP_ROOT . '/app/views/inc/header.php'; ?>

<div class="card">
    <h1 style="color: #007bff;">Privacy Policy</h1>

    <div style="margin-top: 30px; color: #555;">
        <p>Your privacy is important to us. This is a demo privacy policy representing how data would be handled on this platform.</p>

        <h3>1. Information We Collect</h3>
        <p>We collect information you provide directly to us, such as when you create or modify your account, request on-demand services, contact customer support, or otherwise communicate with us. This includes names, emails, addresses, and medical specialties.</p>

        <h3>2. Medical Information & Chat Data</h3>
        <p>Messages sent through the appointment chat feature and digital prescriptions generated by clinics are stored securely in our database. We do not share this data with third-party advertisers. Video calls utilize peer-to-peer or secure server routing via Jitsi Meet and are not recorded by our platform.</p>

        <h3>3. Cookies and Tracking</h3>
        <p>We use strict, secure HTTPOnly cookies solely for managing your authenticated session and protecting against Cross-Site Request Forgery (CSRF). We do not use third-party tracking cookies.</p>

        <h3>4. Security</h3>
        <p>We implement bank-grade security measures, including bcrypt password hashing, PDO prepared statements against SQL injection, and strict output sanitization using HTMLPurifier.</p>
    </div>
</div>

<?php require_once APP_ROOT . '/app/views/inc/footer.php'; ?>
